<form method="post" name="formDelete" action="<?php echo $this->losurl()->from('attribute/delete',[],true) ?>">
<input type="hidden" name="confirm" value="1">

<div class="row">
    <div class="col-xs-12">
    	<?php if ($this->entity->getAttributeName() == 'Question') : ?>
        	<p class="alert alert-danger">Please, confirm the deletion of "<strong><?php echo $this->escapeHtml($this->entity->getAttributeDesc()) ?></strong>"?</p>
        <?php else : ?>
        	<p class="alert alert-warning">You cannot delete "<strong><?php echo $this->escapeHtml($this->entity->getAttributeDesc()) ?></strong>". It is a required field.</p>
        <?php endif; ?>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
    	<?php if ($this->entity->getAttributeName() == 'Question') : ?>
        	<button type="submit" class="btn btn-danger">Confirm</button>
        <?php endif; ?>
        <a href="<?php echo $this->losurl()->from('attribute/list',[],true) ?>" class="btn btn-default">Cancel</a>
    </div>
</div>

</form>