<?php
$title = 'Edit Attribute';
$this->headTitle($title);
?>
<h1>
	<span class="title">
		<?php echo $this->escapeHtml($title); ?>
	</span>
	<span class="pull-right"> <a
		href="<?php echo $this->history ? : $this->losUrl()->from('attribute', ['action'=>'list'], true);?>"
		class="btn btn-success" title="Display Attributes">Back</a>
	</span>
</h1>
<hr class="small">
<div class="row">
	<div
		class="col-xs-12 col-sm-10 col-md-8 col-lg-6">
		<?php echo $this->losForm($this->entityForm, true); ?>
	</div>
</div>
