<?php
use Application\Form\View\Helper\Form as FormHelper;

// $this->headScript()->appendFile('/js/RowSorter.js');
$this->headScript()
	->appendFile('/js/jquery-ui.min.js');
$this->headLink()
	->appendStylesheet('/css/jquery-ui/jquery-ui.min.css');

$title = 'Display Attributes';
$this->headTitle($title);
?>
<h1>
	<span class="title">
		<?php echo $this->escapeHtml($title); ?>
	</span>
	<span class="pull-right" style="margin-left: 15px;"> <a
		href="<?php echo $this->history ? : $this->url('lead', array('action' => 'list')); ?>"
		class="btn btn-info" title="Display Leads">Back</a>
	</span> <span class="pull-right"> <a
		href="<?php echo $this->url('attribute/add', array('action' => 'add')); ?>"
		class="btn btn-success" title="Add New Attribute">Add New Attribute</a>
	</span>
</h1>
<hr class="small">
<br />
<div class="row">
	<div class="col-xs-12">
		<div class="view-header row">
			<div class="col-xs-12">
				<div class="pager-header pull-left">
					<?php echo $this->form($this->pager, FormHelper::LAYOUT_HORIZONTAL); ?>
				</div>
				<div class="total-item-count pull-right">
					<?php echo $this->paginatorPosition($this->paginator); ?>
				</div>
			</div>
		</div>
		<div class="questionsgrid clearfix">
			<hr class="small">
			<div class="view-header row">
				<div class="col-xs-12 col-sm-10 col-md-8">
					<div class="formtable-header pull-left" style="width: 100%;">
						<?php
						if (isset($this->filters)) {
							$filters = $this->filters;
							
							$filters->setAttribute('class', 'leadattributeform');
							
							$filters->setAttribute('id', 'leadAttributeFilterForm');
							
							echo $this->form(null, \Application\Form\View\Helper\Form::LAYOUT_INLINE)
								->openTag($filters);
							
							foreach ( $filters as $filter ) {
								echo $this->formRow($filter);
							}
							
							echo $this->form()
								->closeTag($filter);
						}
						?>
					</div>
				</div>
				<?php if ($this->sort == 'attributeOrder'): ?>
					<div class="col-xs-12 col-sm-2 col-md-4">
					<div class="formtable-header pull-right">
						<form class="form-inline">
							<button id="refresh" type="button" class="btn btn-info">Refresh</button>
						</form>
					</div>
				</div>
				<?php endif; ?>
			</div>
			<hr class="small">
			<table class="table table-hover table-striped" id="questionstable">
				<thead>
					<tr>
						<?php if ($this->sortable): ?><th class="handle"></th><?php endif; ?>
						<?php
						foreach ( $this->ui ['table'] as $field => $ui ) :
							$selected = $this->sort == $field;
							$rorder = $this->order == 'asc' ? 'desc' : 'asc';
							?>
						<th class="col-xs-<?php echo $ui['col']; ?> <?php echo $field; ?>">
						<?php if ($ui['sort']) : ?>
						<a class="sort <?php if ($selected) : echo "selected"; endif; ?>"
							title="Sort by <?php echo $ui['label']; ?>"
							href="<?php echo $this->url('attribute', array('action' => 'list'), array('query' => array_merge($this->query, array('page' => $this->page, 'sort' => $field, 'order' => ($selected ? $rorder : $this->order)))), true); ?>">
								<span>
						<?php echo $ui['label']; ?> <span
									class="glyphicon <?php echo $this->order; ?>"
									aria-hidden="true"></span>
							</span>
						</a>
						<?php else: echo $ui['label']; endif; ?>
						</th>
						<?php endforeach; ?>
						<th class="action col-xs-2 text-right">Actions</th>
					</tr>
				</thead>
				<tbody class="sortable">
	    		<?php foreach ($this->paginator as $entity): $numleads = $entity->getCount(); $question = $entity->getAttributeName() == 'Question'; ?>
	        		<tr class="attributeitem"
						id="<?php echo $entity->getId(); ?>">
						<?php if ($this->sortable): ?><td class="handle"></td><?php endif; ?>
						<td class="col-xs-1 attributeOrder"><div class="sortable-order"><?php echo $entity->getAttributeOrder(); ?></div></td>
						<!--  <td class="col-xs-2 attributeName"><?php echo $entity->getAttributeName(); ?></td> -->
						<td
							class="col-xs-<?php echo $this->ui['table']['attributeDesc']['col']; ?> attributeDesc"><?php echo $entity->getAttributeDesc(); ?></td>
						<td class="col-xs-1 count"><?php echo $numleads; ?></td>
						<td class="action col-xs-2 text-right">
							<?php if ($this->isAdmin) : ?><a <?php if (! $numleads || ! $question) : ?>
							class="disabled btn btn-xs btn-info" onclick="return false;"
							<?php else: ?> class="btn btn-xs btn-info" <?php endif; ?>
							href="<?php echo $this->losUrl()->from('attribute/merge',['id'=>$entity->getId()], true)?>"
							title="Merge Attribute" class="btn btn-xs btn-info"><?php echo $this->losIcon('glyphicon-duplicate') ?></a><?php endif; ?>
							
							<a
							href="<?php echo $this->losUrl()->from('attribute/edit',['id'=>$entity->getId()], true)?>"
							title="Edit Attribute" class="btn btn-xs btn-success"><?php echo $this->losIcon('glyphicon-edit') ?></a>
							
							<?php if ($this->isAdmin) : ?>
								<a <?php if (! $question) : ?>
							class="disabled btn btn-xs btn-danger" onclick="return false;"
							<?php elseif ($numleads) : ?> class="btn btn-xs btn-danger"
							onclick="warn_before_delete(this); return false;" <?php else: ?>
							class="btn btn-xs btn-warning" <?php endif; ?>
							href="<?php echo $this->losUrl()->from('attribute/delete',['id'=>$entity->getId()], true)?>"
							title="Delete Attribute" <?php if ($numleads) : ?>
							class="btn btn-xs btn-danger" <?php else: ?>
							class="btn btn-xs btn-warning" <?php endif; ?>>
										<?php echo $this->losIcon('glyphicon-remove')?>
									</a>
								<?php endif; ?>
							<input type="hidden" class="identifier"
							value="<?php echo $entity->getId();?>" />
						</td>
					</tr>
				<?php endforeach;?>
				</tbody>
			</table>
			<input id="page" type="hidden" value="<?php echo $this->page; ?>" />
			<input id="order" type="hidden" value="<?php echo $this->order; ?>" />
			<input id="limit" type="hidden"
				value="<?php echo $this->pager->get('limit')->getValue(); ?>" />
			<hr>
		</div>
	</div>
</div>
<?php if ($this->paginator->count() > 1):?>
<div class="row">
	<div class="col-xs-12 text-center"><?php echo $this->losPaginationControl($this->paginator,'Sliding',null,['query'=>$this->query]); ?></div>
</div>
<?php endif?>
<?php if ($this->sort == 'attributeOrder'): ?>
<script type="text/javascript">
	$(function(){
		var pageNo = $('#page').val() ? Math.max(0, parseInt($('#page').val()) - 1) : 0;
		var pageLimit = $('#limit').val() ? parseInt($('#limit').val()) : 10;
		var _start = (pageNo && pageLimit) ? (pageNo * pageLimit) : 0;
		var _order = $('#order').val() ? $('#order').val() : 'asc'; 
		$(".sortable").sortTable({
			revert: true,
			handle: '.handle',
			_start: _start,
			_order: _order
		});
		$('#refresh').click(function(){
			location.reload(true);
		});
	});
</script>
<?php endif; ?>
<script type="text/javascript">
	function warn_before_delete(el)
	{
		var url = el.href;
		var r = confirm('Deleting this attribute will remove it from live leads.  Are you sure?');
		if (r == true) {
		    window.location.href = url;
		} else {
		    return false;
		}
	}
</script>