<?php
use Application\Form\View\Helper\Form as FormHelper;

$title = 'Display Attributes';
$this->headTitle($title);
?>
<h1>
<?php echo $this->escapeHtml($title); ?>
	<span class="pull-right" style="margin-left: 15px;"> <a
		href="<?php echo $this->url('lead', array('action' => 'list')); ?>"
		class="btn btn-info" title="Display Leads">Back</a>
	</span> <span class="pull-right"> <a
		href="<?php echo $this->url('attribute/add', array('action' => 'add')); ?>"
		class="btn btn-success" title="Add New Attribute">Add New Attribute</a>
	</span>
</h1>
<hr class="small">
<br />
<div class="row">
	<div class="col-xs-12">
		<div class="view-header row">
			<div class="col-xs-12">
				<div class="pager-header pull-left">
					<?php echo $this->form($this->pager, FormHelper::LAYOUT_HORIZONTAL); ?>
				</div>
				<div class="total-item-count pull-right">
					<?php echo $this->paginatorPosition($this->paginator); ?>
				</div>
			</div>
		</div>
		<div class="questionsgrid clearfix">
			<hr class="small">
			<table class="table table-hover table-striped sel"
				id="questionstable">
				<thead>
					<tr>
						<?php
						foreach ($this->ui['table'] as $field => $ui) :
							$selected = $this->sort == $field;
							$rorder = $this->order == 'asc' ? 'desc' : 'asc';
							?>
						<th class="col-xs-<?php echo $ui['col']; ?> <?php echo $field; ?>">
						<?php if ($ui['sort']) : ?>
						<a class="sort <?php if ($selected) : echo "selected"; endif; ?>"
							title="Sort by <?php echo $ui['label']; ?>"
							href="<?php echo $this->url('attribute', array('action' => 'list'), array('query' => array_merge($this->query, array('page' => $this->page, 'sort' => $field, 'order' => ($selected ? $rorder : $this->order)))), true); ?>">
								<span>
						<?php echo $ui['label']; ?> <span
									class="glyphicon <?php echo $this->order; ?>"
									aria-hidden="true"></span>
							</span>
						</a>
						<?php else: echo $ui['label']; endif; ?>
						</th>
						<?php endforeach; ?>
						<th class="action col-xs-1 text-right">Action</th>
					</tr>
				</thead>
				<tbody>
	    		<?php foreach ($this->paginator as $entity):?>
	        		<tr class="attributeitem">
						<td class="col-xs-2 name"><?php echo $entity->getAttributeName(); ?></td>
						<td class="col-xs-9 description"><?php echo $entity->getAttributeDesc(); ?></td>
						<td class="action col-xs-1 text-right"><a
							href="<?php echo $this->losUrl()->from('attribute/edit',['id'=>$entity->getId()], false)?>"
							title="Edit Question" class="btn btn-xs btn-warning"><?php echo $this->losIcon('glyphicon-edit') ?></a>
						</td>
					</tr>
				<?php endforeach;?>
				</tbody>
			</table>
			<hr>
		</div>
	</div>
</div>
<?php if ($this->paginator->count() > 1):?>
<div class="row">
	<div class="col-xs-12 text-center"><?php echo $this->losPaginationControl($this->paginator,'Sliding',null,['query'=>$this->query]); ?></div>
</div>
<?php endif?>
