<?php
// module/Appliation/view/application/error/index.phtml:
$title = 'Oops!';
$this->headTitle($title);
?>
<div class="row content">
	<div class="col-md-12">
		<section class="main">
			<h1>
				<span class="title">
					<?php echo $this->escapeHtml($title); ?>
				</span>			
			</h1>
		</section>
		<section class="desc">
			<h4>
				It looks like an error occurred. Would you like to go to <a
					href="<?php echo $this->url('home'); ?>">homepage</a> instead?
			</h4>
		</section>
	</div>
</div>