<?php
use Application\Utility\Helper;
/* @var $container Zend\Navigation\Navigation */
$container = $this->container;
?>
<ul
	class="<?php echo $this->navigation($container)->menu()->getUlClass(); ?>">
    <?php foreach ($container as $page): ?>
        <?php if (!$this->navigation()->accept($page)) continue; ?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php $hasChildren = $page->hasPages()?>
        <?php if (!$hasChildren): ?>
            <li
		class="<?php echo Helper::slugify($page->getLabel()); if ($page->isActive()) echo ' active'; ?>">
		<a class="nav-header"
		title="<?php echo $this->escapeHtml($this->translate($page->getLabel(),$this->navigation($container)->getTranslatorTextDomain())); ?>"
		href="<?php echo $page->getHref() ?>"
		<?php if ($page->getTarget() != ""): ?>
		target="<?php echo $page->getTarget(); ?>" <?php endif; ?>>
                        <?php if ($page->get("icon") !== ""): ?>
                        <span class="<?php echo $page->get("icon"); ?>"></span>
                    <?php endif; ?>
                       	<span class="menu-label">
                    		<?php echo $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?>
                    	</span>
	</a>
	</li>
        <?php else: ?>
            <?php
						// check if access is allowed at least one item
						$access = false;
						foreach ( $page->getPages() as $child ) {
							if ($this->navigation()
								->accept($child) && $child->get("separator") !== true) {
								$access = true;
							}
						}
						if ($access) :
							?>
                <li
		class="dropdown <?php echo Helper::slugify($page->getLabel()); if ($page->isActive(true)) echo ' active' ?>">
		<a class="dropdown-toggle" data-toggle="dropdown" href="#"
		title="<?php echo $this->escapeHtml($this->translate($page->getLabel(),$this->navigation($container)->getTranslatorTextDomain())); ?>">
                        <?php if ($page->get("icon") !== ""): ?>
                            <span
			class="<?php echo $page->get("icon"); ?>"></span>
                        <?php endif; ?>
                        <span class="menu-label">
	                        <?php echo $this->escapeHtml($this->translate($page->getLabel(),$this->navigation($container)->getTranslatorTextDomain())); ?>
	                        <b class="caret"></b>
		</span>
	</a>
		<ul class="dropdown-menu">
                        <?php foreach ($page->getPages() as $child): ?>
                            <?php if (!$this->navigation()->accept($child)) continue; ?>
                            <?php if ($child->get("separator") === true): ?>
                                <li class="divider"></li>
                                    <?php
									continue;
								
                                endif;
								?>
                            <li
				<?php if ($child->isActive()) echo ' class="active"' ?>><a
				href="<?php echo $child->getHref() ?>"
				title="<?php echo $this->escapeHtml($this->translate($page->getLabel(),$this->navigation($container)->getTranslatorTextDomain())); ?>"
				<?php if ($child->getTarget() != ""): ?>
				target="<?php echo $child->getTarget(); ?>" <?php endif; ?>>
                                        <?php if ($child->get("icon") !== ""): ?>
                                        <span
					class="<?php echo $child->get("icon"); ?>"></span>
                                    <?php endif; ?>
                                    <?php echo $this->escapeHtml($this->translate($child->getLabel(),$this->navigation($container)->getTranslatorTextDomain())); ?>
                                </a></li>
                        <?php endforeach ?>
                    </ul>
	</li>   
            <?php endif; ?>
        <?php endif; ?>
    <?php endforeach; ?>
    <li id="collapse-menu" class="hide-if-no-js"><span>Collapse menu</span>
		<div id="collapse-button">
			<div></div>
		</div></li>
</ul>