<?php
// module/Api/view/api/api/list.phtml:
/**
 *
 * @var /Api/Entity/Api
 */
$title = 'API Options';
$this->headTitle($title);
?>
<h1>
	<span class="title">
		<?php echo $this->escapeHtml($title); ?>
	</span>
	<span class="pull-right"> <a class="btn btn-info"
		href="<?php echo $this->history ? : $this->url('home', array('action'=>'index'));?>">Back</a>
	</span>
</h1>
<hr class="small">
<table id="list" class="table table-hover table-striped">
	<thead>
		<tr>
			<th class="col-xs-4">Nome</th>
			<th class="col-xs-7">Description</th>
			<th class="col-xs-1"></th>
		</tr>
	</thead>
	<tbody>
    <?php foreach ($this->paginator as $entity):?>
        <tr class="apiitem">
			<td><?= $entity->getName()?></td>
			<td><?= $entity->getDescription()?></td>
			<td class="text-right"><a
				href="<?php echo $this->losUrl()->from('api/edit',['id'=>$entity->getId()],true)?>"
				class="btn btn-sm btn-warning pull-right"><?= $this->losIcon('glyphicon-edit') ?></a>
			</td>
		</tr>
    <?php endforeach;?>
</tbody>
</table>

<?php if ($this->paginator->count() > 1):?>
<div class="row">
	<div class="col-xs-12 text-center"><?= $this->losPaginationControl($this->paginator,'Sliding',null,['query'=>$this->query]); ?></div>
</div>
<?php endif?>
