<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array (
		'ReportTest\Framework\TestCase' => __DIR__ . '/tests/Report/Framework/TestCase.php',
		'ReportTest\SampleTest' => __DIR__ . '/tests/Report/SampleTest.php',
		'Report\Provider\ResultAwareTrait' => __DIR__ . '/src/Report/Provider/ResultAwareTrait.php',
		'Report\Controller\ResultController' => __DIR__ . '/src/Report/Controller/ResultController.php',
		'Report\Controller\Plugin\HighChart' => __DIR__ . '/src/Report/Controller/Plugin/HighChart.php',
		'Report\Controller\Plugin\Factory\HighChartFactory' => __DIR__ . '/src/Report/Controller/Plugin/Factory/HighChartFactory.php',
		'Report\Controller\ReportController' => __DIR__ . '/src/Report/Controller/ReportController.php',
		'Report\Service\Report' => __DIR__ . '/src/Report/Service/Report.php',
		'Report\Service\Result' => __DIR__ . '/src/Report/Service/Result.php',
		'Report\Entity\Report' => __DIR__ . '/src/Report/Entity/Report.php',
		'Report\Entity\Listener\ReportListener' => __DIR__ . '/src/Report/Entity/Listener/ReportListener.php',
		'Report\Event\Listener\ReportListener' => __DIR__ . '/src/Report/Event/Listener/ReportListener.php',
		'Report\Form\ListForm' => __DIR__ . '/src/Report/Form/ListForm.php',
		'Report\Form\Factory\FilterFormFactory' => __DIR__ . '/src/Report/Form/Factory/FilterFormFactory.php',
		'Report\Form\Factory\AddFormFactory' => __DIR__ . '/src/Report/Form/Factory/AddFormFactory.php',
		'Report\Form\Factory\EditFormFactory' => __DIR__ . '/src/Report/Form/Factory/EditFormFactory.php',
		'Report\Form\Factory\ListFormFactory' => __DIR__ . '/src/Report/Form/Factory/ListFormFactory.php',
		'Report\Form\InputFilter\AddFormInputFilter' => __DIR__ . '/src/Report/Form/InputFilter/AddFormInputFilter.php',
		'Report\Form\EditForm' => __DIR__ . '/src/Report/Form/EditForm.php' 
);
