<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Email\Module'                        => __DIR__ . '/Module.php',
    'Email\Controller\EmailController' => __DIR__ . '/src/Email/Controller/EmailController.php',
    'EmailTest\Framework\TestCase'        => __DIR__ . '/tests/Email/Framework/TestCase.php',
    'EmailTest\SampleTest'                => __DIR__ . '/tests/Email/SampleTest.php',
);
