<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array (
		'Agent\Module' => __DIR__ . '/Module.php',
		'Agent\Controller\AgentController' => __DIR__ . '/src/Agent/Controller/AgentController.php',
		'AgentTest\Framework\TestCase' => __DIR__ . '/tests/Agent/Framework/TestCase.php',
		'AgentTest\SampleTest' => __DIR__ . '/tests/Agent/SampleTest.php' 
);
