<form method="post" name="formSubmit" action="<?php echo $this->losurl()->from('lead/submit',[],true) ?>">
<input type="hidden" name="confirm" value="1">

<div class="row">
    <div class="col-xs-12">
        <p class="alert alert-success">Please, confirm the submission of Lead #"<strong><?php echo $this->escapeHtml($this->entity->getId()) ?></strong>"?</p>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <button type="submit" class="btn btn-success">Confirm</button>
        <a href="<?php echo $this->losurl()->from('lead/list',[],true) ?>" class="btn btn-default">Cancel</a>
    </div>
</div>

</form>