<?php
// module/Lead/view/lead/lead/view.phtml:
/* @var $entity \Lead\Entity\Lead */
$entity = $this->entity;
$title = 'View Lead';
$this->headTitle($title);
?>
<h1>
	<span class="title">
		<?php echo $this->escapeHtml($title); ?>
	</span>
	<span class="pull-right"> <a class="btn btn-info"
		style="margin-left: 15px;"
		href="<?php echo $this->history ? : $this->losUrl()->from('lead', ['action'=>'list'], true);?>">Back</a>
	</span> <span class="pull-right"> <a class="btn btn-danger"
		style="margin-left: 15px;"
		href="<?php echo $this->url('lead/delete', array('action'=>'delete', 'id' => $entity->getId()));?>">Delete
			Lead</a>
	</span> <span class="pull-right"> <a class="btn btn-success"
		style="margin-left: 15px;"
		href="<?php echo $this->url('lead/edit', array('action'=>'edit', 'id' => $entity->getId()));?>">Edit
			Lead</a>
	</span> <span class="pull-right"> <a class="btn btn-primary"
		href="<?php echo $this->url('lead/submit', array('action'=>'submit', 'id' => $entity->getId()));?>">Submit
			Lead</a>
	</span>
</h1>
<?php
$detail = $entity->getAttributes(false);
$account = $entity->getAccount();
$events = $entity->getEvents();
?>
<div class="row content-row">
	<div class="col-md-12">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">
					<?php echo $this->translate('Lead Summary')?>
				</h3>
			</div>
			<div class="panel-body">
				<table class="table table-hover table-condensed nomargin">
					<tr>
						<th>Created</th>
						<td><?php echo date_format($entity->getTimecreated(), 'd M, Y h:i A'); ?></td>
					</tr>
					<tr>
						<th>Referrer</th>
						<td><a target="_blank" title="Referrer"
							href="<?php echo $entity->getReferrer(); ?>"><?php echo $entity->getReferrer(); ?></a></td>
					</tr>
					<tr>
						<th>I.P. Address</th>
						<td><?php echo $entity->getIpaddress(); ?></td>
					</tr>
					<tr>
						<th>Account</th>
						<td><?php echo $account ? "<a href=\"" . $this->url('account/view', array('action'=>'view', 'id' => $account->getId())) . "\">" . $account->getName() . "</a>" : 'None'; ?></td>
					</tr>
				</table>
			</div>
		</div>
	</div>
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
					<?php echo $this->translate('Lead Details')?>
				</h3>
			</div>
			<div class="panel-body">
				<table class="table table-hover table-condensed nomargin">
					<?php
					
foreach ( $detail as $attributeValue ) :
						if ($attributeValue) :
							$attribute = $attributeValue->getAttribute();
							if ($attribute) :
								?>
					<tr>
						<th><?php echo $attribute->getAttributeDesc(); ?></th>
						<td><?php echo $attributeValue->getValue(); ?></td>
					</tr>
					<?php endif; endif; endforeach; ?>
				</table>
			</div>
		</div>
	</div>
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
					<?php echo $this->translate('Lead History')?>
				</h3>
			</div>
			<div class="panel-body">
				<table class="table table-hover table-condensed nomargin">
					<thead>
						<tr>
							<th>Event</th>
							<th>Message</th>
							<th>Date</th>
						</tr>
					</thead>
					<?php foreach ($events as $ev) : $event = $ev->getEvent(); ?>
						<tr>
						<th><?php echo $event->getEvent(); ?></th>
						<td><?php echo $event->getMessage(); ?></td>
						<td><?php echo date_format($event->getOccurred(), 'd M, Y h:i A'); ?></td>
					</tr>
					<?php endforeach; ?>
				</table>
			</div>
		</div>
	</div>

</div>