<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Lead\Module'                        => __DIR__ . '/Module.php',
    'Lead\Controller\LeadController' => __DIR__ . '/src/Lead/Controller/LeadController.php',
    'LeadTest\Framework\TestCase'        => __DIR__ . '/tests/Lead/Framework/TestCase.php',
    'LeadTest\SampleTest'                => __DIR__ . '/tests/Lead/SampleTest.php',
);
