<?php
$entity = $this->entity;
$title = 'Add Account';
$this->headTitle($title);
?>
<div class="row">
	<div class="col-xs-12">
		<div class="pull-left">
			<?php $this->entityNav(); ?>
		</div>
	</div>
</div>
<h1>
<?php echo $this->escapeHtml($title); ?>
<span class="pull-right"> <a
		href="<?php echo $this->url('account', array('action' => 'list')); ?>"
		class="btn btn-success" title="Display Accounts">Back</a>
	</span>
</h1>
<hr class="small">
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
						<?php echo $this->translate('Add a new Account')?>
					</h3>
			</div>
			<div class="panel-body">
				<?php echo $this->losForm($this->entityForm); ?>
			</div>
		</div>

	</div>
</div>
