<?php
/**
 *
 * @var /Account/Entity/Account
 */
$entity = $this->entity;
$title = $entity->getName();
$this->headTitle($title);
?>
<div class="row">
	<div class="col-xs-12">
		<div class="pull-left">
			<?php $this->entityNav(); ?>
		</div>
	</div>
</div>
<h1>
<?php echo $this->escapeHtml($title); ?>
<span class="pull-right"> <a class="btn btn-info"
		href="<?php echo $this->url('account', array('action'=>'list'));?>">Back</a>
	</span>
</h1>
<hr class="small">
<form method="post" name="formDelete"
	action="<?php echo $this->losurl()->from('cliente/delete',[],true) ?>">
	<input type="hidden" name="confirm" value="1">

	<div class="row">
		<div class="col-xs-12">
			<p class="alert alert-danger">
				Please, confirm the deletion of "<strong><?php echo $this->escapeHtml($this->entity->getId()) ?></strong>"?
			</p>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12">
			<button type="submit" class="btn btn-danger">Confirm</button>
			<a href="<?php echo $this->losurl()->from('cliente/list',[],true) ?>"
				class="btn btn-default">Cancel</a>
		</div>
	</div>

</form>