<?php
$entity = $this->entity;
$title = 'Account Settings';
$this->headTitle($title);
?>
<div class="row">
	<div class="col-xs-12">
		<div class="pull-left">
			<?php $this->entityNav(); ?>
		</div>
	</div>
</div>
<h1>
	<span class="title">
		<?php echo $this->escapeHtml($title); ?>
	</span>
	<span class="pull-right"> <a
		href="<?php echo $this->history ? : $this->url('account', array('action' => 'list')); ?>"
		class="btn btn-success" title="Display Accounts">Back</a>
	</span>
</h1>
<hr class="small">
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
						<?php echo $this->translate('Account Settings')?>
					</h3>
			</div>
			<div class="panel-body">
				<?php echo $this->losForm($this->entityForm); ?>
			</div>
			<div class="panel-footer">
				<p>
					<a
						href="<?php echo $this->url('account/application/api/edit', array('action' => 'edit', 'id' => $entity->getId())); ?>">Edit
						API Settings</a>
				</p>
			</div>
		</div>

	</div>
</div>
