<?php
use Application\Form\View\Helper\Form as FormHelper;

$form = $this->form;
if ($form->has('confirm')) {
	include ('confirm.phtml');
	return;
}
?>
<?php

$title = 'Display Accounts';
$this->headTitle($title);
?>
<div class="row">
	<div class="col-xs-12">
		<div class="pull-left">
			<?php $this->entityNav(); ?>
		</div>
	</div>
</div>
<h1>
<?php echo $this->escapeHtml($title); ?>
<span class="pull-right"> <a
		href="<?php echo $this->url('account/add', array('action' => 'add')); ?>"
		class="btn btn-success" title="Add New Account">Add New Account</a>
	</span>
</h1>
<hr class="small">
<br />
<div class="row">
	<div class="col-xs-12">
		<div class="formtable-header pull-right">
			<?php
			if (isset($this->filters)) {
				$filters = $this->filters;
				
				$filters->setAttribute('class', 'accountform');
				
				$filters->setAttribute('id', 'accountFilterForm');
				
				echo $this->form(null, 
						\Application\Form\View\Helper\Form::LAYOUT_INLINE)->openTag(
						$filters);
				
				foreach ($filters as $name => $filter) {
					switch ($name) {
						case 'description':
							echo '<div style="width:75%; float:right;">' .
									 $this->formRow($filter) . '</div>';
							break;
						default:
							echo '<div style="float:right;">' .
									 $this->formRow($filter) . '</div>';
							break;
					}
				}
				
				echo $this->form()->closeTag($filter);
			}
			?>
		</div>
		<div class="pager-header pull-left">
			<?php echo $this->form($this->pager, FormHelper::LAYOUT_HORIZONTAL); ?>
		</div>
	</div>
	<div class="col-xs-12">
		<hr class="small clearfix">
<?php
$form->setAttribute('class', 'accountform');
$form->setAttribute('id', 'accountForm');
$form->prepare();
echo $this->form(null, \Application\Form\View\Helper\Form::LAYOUT_INLINE)->openTag(
		$form);
?>
<?php if ($this->isAllowed('resource', 'delete')) : ?>
	<div class="batch-assign-header pull-left">
		<?php echo $this->formRow($form->get('submit')); ?>
	</div>
<?php endif; ?>
		<table class="table table-hover table-striped sel" id="accountstable">
			<thead>
				<tr>
					<th class="account.id col-xs-1">
						<?php if ($this->isAllowed('resource', 'delete')): ?><input
						type="checkbox" class="selall">&nbsp;&nbsp;&nbsp;<?php endif; ?>ID</th>
			<?php
			foreach ($this->ui['table'] as $field => $ui) :
				$selected = $this->sort == $field;
				$rorder = $this->order == 'asc' ? 'desc' : 'asc';
				?>
			<th class="col-xs-<?php echo $ui['col']; ?> <?php echo $field; ?>">
			<?php if ($ui['sort']) : ?>
			<a class="sort <?php if ($selected) : echo "selected"; endif; ?>"
						title="Sort by <?php echo $ui['label']; ?>"
						href="<?php echo $this->url('account', array('action' => 'list'), array('query' => array_merge($this->query, array('page' => $this->page, 'sort' => $field, 'order' => ($selected ? $rorder : $this->order)))), true); ?>">
							<span>
			<?php echo $ui['label']; ?> <span
								class="glyphicon <?php echo $this->order; ?>" aria-hidden="true"></span>
						</span>
					</a>
			<?php else: echo $ui['label']; endif; ?>
			</th>
			<?php endforeach; ?>
			<th class="action col-xs-1 text-right">Action</th>
				</tr>
			</thead>
			<tbody>
    <?php foreach ($this->paginator as $entity):?>
				<tr class="accountitem">
					<td class="account.id col-xs-1"><?php if ($this->isAllowed('resource', 'delete')) : ?><div
							class="checkbox"><?php echo $this->formElement($form->get("sel[" . $entity->getId() . "]")); ?></div>&nbsp;&nbsp;&nbsp;<?php endif; ?><?php echo $entity->getId(); ?></td>
					<td class="col-xs-2 name"><a
						href="<?php echo $this->url('account/application', ['action'=>'view', 'id' => $entity->getId()]);?>"><?php echo $entity->getName(); ?></a></td>
					<td class="col-xs-4 description"><?php echo $entity->getDescription(); ?></td>
					<td class="col-xs-2 apis"><a
						href="<?php echo $this->losUrl()->from('account/application/api/edit',['id'=>$entity->getId()], false)?>"><?php echo implode(", ", array_map(function($api){return $api->getName();}, $entity->getApis())); ?></a></td>
					<td class="col-xs-2 leads"><?php echo count($entity->getleads()); ?></td>
					<td class="action col-xs-1 text-right"><a
						href="<?php echo $this->losUrl()->from('account/view',['id'=>$entity->getId()], false)?>"
						title="View Account" class="btn btn-xs btn-info"><?php echo $this->losIcon('glyphicon-eye-open') ?></a>
						<a
						href="<?php echo $this->losUrl()->from('account/edit',['id'=>$entity->getId()], false)?>"
						title="Edit Account" class="btn btn-xs btn-warning"><?php echo $this->losIcon('glyphicon-edit') ?></a>
					</td>
				</tr>
		<?php endforeach;?>

			
			</tbody>
		</table>
		<hr>
	<?php echo $this->form()->closeTag(); ?>
	</div>
</div>
<?php if ($this->paginator->count() > 1):?>
<div class="row">
	<div class="col-xs-12 text-center"><?php echo $this->losPaginationControl($this->paginator,'Sliding',null,['query'=>$this->query]); ?></div>
</div>
<?php endif?>
