<h3><?php echo sprintf($this->translate('Change Password for %s'), $this->zfcUserDisplayName()); ?></h3>
<?php $status = isset($this->status) ? $this->status : $status; ?>
<?php if ($status === true) : ?>
<div class="alert alert-success"><?php echo $this->translate('Password changed successfully.');?></div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error"><?php echo $this->translate('Unable to update your password. Please try again.'); ?></div>
<?php endif; ?>
<?php

$form = $this->changePasswordForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');
$form->setAttribute('autocomplete', 'off');

$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()
	->getEmail());

echo $this->form()->openTag($form);

?>
<div class="tableform-wrapper">
	<table class="table">

		<tr>
			<td>
				<div class="form-group">
				<?php echo $this->formLabel($form->get('credential')); ?>
				<?php
				echo $this->formInput(
						$form->get('credential')
							->setAttribute('class', 'form-control')) .
						 $this->formElementErrors($form->get('credential'));
				?>
			</div>
			</td>
		</tr>

		<tr>
			<td>
				<div class="form-group">
				<?php echo $this->formLabel($form->get('newCredential')); ?>
				<?php
				echo $this->formInput(
						$form->get('newCredential')
							->setAttribute('class', 'form-control')) .
						 $this->formElementErrors($form->get('newCredential'));
				?>
			</div>
			</td>
		</tr>

		<tr>
			<td>
				<div class="form-group">
				<?php echo $this->formLabel($form->get('newCredentialVerify')); ?>
				<?php
				echo $this->formInput(
						$form->get('newCredentialVerify')
							->setAttribute('class', 'form-control')) . $this->formElementErrors(
						$form->get('newCredentialVerify'));
				?>
			</div>
			</td>
		</tr>

		<tr>
			<td>
		<?php
		// echo $this->formInput($form->get('csrf'));
		echo $this->formInput($form->get('submit'));
		?>
		</td>
		</tr>
	</table>

	<p><?php echo $this->formElementErrors($form->get('identity')); ?></p>

	<p><?php echo $this->formInput($form->get('identity')); ?></p>
</div>

<?php echo $this->form()->closeTag(); ?>
