<h1><?php echo $this->translate('Sign In'); ?></h1>
<hr class="thin">

<div class="row">
	<div
		class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
		<?php
		$form = $this->loginForm;
		$form->prepare();
		$form->setAttribute('action', $this->url('zfcuser/login'));
		$form->setAttribute('method', 'post');
		$form->setAttribute('autocomplete', 'off');
		?>
		<?php echo $this->form()->openTag($form)?>
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="tableform-wrapper">
					<table class="table">

						<tr>
							<td><?php echo $this->formrow($form->get('identity')); ?></td>
						</tr>

						<tr>
							<td><?php echo $this->formrow($form->get('credential')); ?></td>
						</tr>

						<tr>
							<td><?php echo $this->formButton($form->get('submit')->setAttribute('class', 'btn btn-primary')); ?></td>
						</tr>

					</table>
				</div>
			</div>
		</div>
		<?php if ($this->redirect): ?>
		<input type="hidden" name="redirect"
			value="<?php echo $this->escapeHtml($this->redirect) ?>" />
		<?php endif ?>

		<?php echo $this->form()->closeTag()?>

		<?php if ($this->enableRegistration) : ?>
		<table class="table">
			<tr>
				<td>
				<?php echo $this->translate('Not registered?'); ?> <a
					href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->escapeUrl($this->redirect) : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
				</td>
			</tr>
		</table>
		<?php endif; ?>
	</div>
</div>