<h1><?php echo $this->translate('Sign In'); ?></h1>

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('autocomplete', 'off');
?>

<?php echo $this->form()->openTag($form) ?>
<div class="tableform-wrapper">
	<table class="table">
	
		<tr>
			<td><?php echo $this->formrow($form->get('identity')); ?></td>
		</tr>
	
		<tr>
			<td><?php echo $this->formrow($form->get('credential')); ?></td>
		</tr>
		
		<tr>
			<td><?php echo $this->formButton($form->get('submit')); ?></td>
		</tr>
		
	</table>
</div>
    <?php if ($this->redirect): ?>
    	<input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
	<?php endif ?>

<?php echo $this->form()->closeTag() ?>

<?php if ($this->enableRegistration) : ?>
	<table class="table">
	
		<tr>
			<td>
				<?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->escapeUrl($this->redirect) : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
			</td>
		</tr>
	
	</table>
<?php endif; ?>
