<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array (
		'WebWorksTest\SampleTest' => __DIR__ . '/tests/WebWorks/SampleTest.php',
		'WebWorks\Module' => __DIR__ . '/Module.php',
		'WebWorks\Utility\Utility' => __DIR__ . '/src/WebWorks/Utility/Utility.php',
		'WebWorks\Hydrator\Strategy\SubEntityHydratorStrategy' => __DIR__ . '/src/WebWorks/Hydrator/Strategy/SubEntityHydratorStrategy.php',
		'WebWorks\Hydrator\Strategy\ContactDataAttributesStrategy' => __DIR__ . '/src/WebWorks/Hydrator/Strategy/ContactDataAttributesStrategy.php',
		'WebWorks\Hydrator\Strategy\PhoneNumberStrategy' => __DIR__ . '/src/WebWorks/Hydrator/Strategy/PhoneNumberStrategy.php',
		'WebWorks\Hydrator\Strategy\DisplayFieldHydratorStrategy' => __DIR__ . '/src/WebWorks/Hydrator/Strategy/DisplayFieldHydratorStrategy.php',
		'WebWorks\Hydrator\Strategy\MapperNamingStrategy' => __DIR__ . '/src/WebWorks/Hydrator/Strategy/MapperNamingStrategy.php',
		'WebWorks\Hydrator\Factory\PersonalDataHydratorFactory' => __DIR__ . '/src/WebWorks/Hydrator/Factory/PersonalDataHydratorFactory.php',
		'WebWorks\Hydrator\Factory\ApplicationDataHydratorFactory' => __DIR__ . '/src/WebWorks/Hydrator/Factory/ApplicationDataHydratorFactory.php',
		'WebWorks\Hydrator\Factory\WebWorksDataHydratorFactory' => __DIR__ . '/src/WebWorks/Hydrator/Factory/WebWorksDataHydratorFactory.php',
		'WebWorks\Mapper\WebWorksDataMapper' => __DIR__ . '/src/WebWorks/Mapper/WebWorksDataMapper.php',
		'WebWorks\Controller\Factory\XMLClientControllerFactory' => __DIR__ . '/src/WebWorks/Controller/Factory/XMLClientControllerFactory.php',
		'WebWorks\Service\AbstractWebWorksService' => __DIR__ . '/src/WebWorks/Service/AbstractWebWorksService.php',
		'WebWorks\Service\Factory\ImportXMLServiceFactory' => __DIR__ . '/src/WebWorks/Service/Factory/ImportXMLServiceFactory.php',
		'WebWorks\Entity\ApplicationData\DisplayFields\DisplayField' => __DIR__ . '/src/WebWorks/Entity/ApplicationData/DisplayFields/DisplayField.php',
		'WebWorks\Entity\ApplicationData\ApplicationData' => __DIR__ . '/src/WebWorks/Entity/ApplicationData/ApplicationData.php',
		'WebWorks\Entity\PersonalData\PostalAddress' => __DIR__ . '/src/WebWorks/Entity/PersonalData/PostalAddress.php',
		'WebWorks\Entity\PersonalData\ContactData' => __DIR__ . '/src/WebWorks/Entity/PersonalData/ContactData.php',
		'WebWorks\Entity\PersonalData\PersonalData' => __DIR__ . '/src/WebWorks/Entity/PersonalData/PersonalData.php',
		'WebWorks\Entity\PersonalData\PersonName' => __DIR__ . '/src/WebWorks/Entity/PersonalData/PersonName.php',
		'WebWorks\Entity\WebWorksData' => __DIR__ . '/src/WebWorks/Entity/WebWorksData.php',
		'WebWorks\Event\Listener\ImportXMLListener' => __DIR__ . '/src/WebWorks/Event/Listener/ImportXMLListener.php' 
);
