<?php
// module/Lead/view/lead/import/import.phtml:
if (3 === $this->stage) {
	$this->headLink()
		->appendStylesheet('/css/bootstrap-switch.min.css');
	$this->headScript()
		->appendFile('/js/bootstrap-switch.min.js');
}
$title = 'Import Leads';
$this->headTitle($title);
?>
<h1>
<?php echo $this->escapeHtml($title); ?>
<span class="pull-right"> <a class="btn btn-info"
		href="<?php echo $this->url('import', array('action'=>'import'));?>">Back</a>
	</span>
</h1>
<hr>
<ul class="nav nav-pills nav-wizard">
	<li <?php echo ($this->stage == 1) ? ' class="active"' : ''; ?>><a
		href="javacript:void()">Import</a>
		<div class="nav-arrow"></div></li>
	<li <?php echo ($this->stage == 2) ? ' class="active"' : ''; ?>><div
			class="nav-wedge"></div> <a href="javacript:void()">Match</a>
		<div class="nav-arrow"></div></li>
	<li <?php echo ($this->stage == 3) ? ' class="active"' : ''; ?>><div
			class="nav-wedge"></div> <a href="javacript:void()">Review</a>
		<div class="nav-arrow"></div></li>
	<li <?php echo ($this->stage == 4) ? ' class="active"' : ''; ?>><div
			class="nav-wedge"></div> <a href="javacript:void()">Confirm</a></li>
</ul>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('import', array (
		'action' => 'import' 
)));
$form->prepare();

echo $this->form()
	->openTag($form);
?>
<div class="row content-row">
<?php
if ($form->has('match') && 2 === $this->stage) :
	// Stage 2
	include __DIR__ . '/partial/match.php';
 elseif ($form->has('leadsUpload') && 1 === $this->stage) :
	// Stage 1
	include __DIR__ . '/partial/import.php';
 elseif ($this->data && 3 === $this->stage) :
	// Stage 3
	include __DIR__ . '/partial/review.php';
 elseif ($this->data && 4 === $this->stage) :
	// Stage 4
	include __DIR__ . '/partial/confirm.php';
	?>
<?php endif; ?>
</div>
<?php echo $this->form()->closeTag(); ?>