<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Event\Module'                        => __DIR__ . '/Module.php',
    'Event\Controller\EventController' => __DIR__ . '/src/Event/Controller/EventController.php',
    'EventTest\Framework\TestCase'        => __DIR__ . '/tests/Event/Framework/TestCase.php',
    'EventTest\SampleTest'                => __DIR__ . '/tests/Event/SampleTest.php',
);
