<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TenStreet\Module'                        => __DIR__ . '/Module.php',
    'TenStreet\Controller\ClientController' => __DIR__ . '/src/TenStreet/Controller/ClientController.php',
    'TenStreetTest\Framework\TestCase'        => __DIR__ . '/tests/TenStreet/Framework/TestCase.php',
    'TenStreetTest\SampleTest'                => __DIR__ . '/tests/TenStreet/SampleTest.php',
);
