<?php
use Application\Form\View\Helper\Form as FormHelper;

$title = 'Display Reports';
$this->headTitle($title);
?>
<h1>
	<span class="title">
		<?php echo $this->escapeHtml($title); ?>
	</span>
	<span class="pull-right"> <a
		href="<?php echo $this->url('report/add', array('action' => 'add')); ?>"
		class="btn btn-success" title="Create Report">Create Report</a>
	</span>
</h1>
<hr class="small">
<br />
<div class="row formtable-header">
	<div class="col-xs-12">
		<div class="row pager-control">
			<div class="col-xs-6">
				<div class="pager-header pull-left">
							<?php echo $this->form($this->pager, FormHelper::LAYOUT_HORIZONTAL); ?>
						</div>
			</div>
			<div class="col-xs-6">
				<div class="total-item-count pull-right">
							<?php echo $this->paginatorPosition($this->paginator); ?>
						</div>
			</div>
		</div>
	</div>
	<div class="col-xs-12">
		<div class="form-control-group row">
			<div class="col-sm-12 col-md-2">
				<label class="inline">Filters: </label>
			</div>
			<div class="col-sm-12 col-md-10">
				<div class="form-filter">
					<?php
					if (isset($this->filters)) {
						$filters = $this->filters;
						
						$filters->setAttribute('class', 'leadform');
						
						$filters->setAttribute('id', 'reportFilterForm');
						
						echo $this->form(null, \Application\Form\View\Helper\Form::LAYOUT_INLINE)
							->openTag($filters);
						
						foreach ( $filters as $filter ) {
							echo $this->formRow($filter);
						}
						
						echo $this->form()
							->closeTag($filter);
					}
					?>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<?php
	$form = $this->form;
	$form->setAttribute('class', 'reportform');
	$form->setAttribute('id', 'reportForm');
	$form->prepare();
	echo $this->form(null, \Application\Form\View\Helper\Form::LAYOUT_INLINE)
		->openTag($form);
	?>
	<div class="batchleadsForm clearfix col-xs-12">
		<div class="form-control-group row">
			<div class="col-sm-12 col-md-2">
				<label class="inline">Bulk Actions: </label>
			</div>
			<div class="col-sm-12 col-md-10">
				<div class="bulk-actions">
					<?php echo $this->formRow($form->get('account')); ?>
					<?php echo $this->formRow($form->get('bulk_action')); ?>
					<?php echo $this->formRow($form->get('submit')); ?>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xs-12">
		<div class="batchleadsForm clearfix">
			<table class="table table-hover table-striped sel" id="leadstable">
				<thead>
					<tr>
						<th class="lead.id col-xs-1"><input type="checkbox" class="selall"></th>
				<?php
				foreach ( $this->ui ['table'] as $field => $ui ) :
					$selected = $this->sort == $field;
					$rorder = $this->order == 'asc' ? 'desc' : 'asc';
					?>
				<th class="col-xs-<?php echo $ui['col']; ?> <?php echo $field; ?>">
				<?php if ($ui['sort']) : ?>
				<a class="sort <?php if ($selected) : echo "selected"; endif; ?>"
							title="Sort by <?php echo $ui['label']; ?>"
							href="<?php echo $this->url('lead', array('action' => 'list'), array('query' => array_merge($this->query, array('page' => $this->page, 'sort' => $field, 'order' => ($selected ? $rorder : $this->order)))), true); ?>">
								<span>
				<?php echo $ui['label']; ?> <span
									class="glyphicon <?php echo $this->order; ?>"
									aria-hidden="true"></span>
							</span>
						</a>
				<?php else: echo $ui['label']; endif; ?>
				</th>
				<?php endforeach; ?>
				<th class="action col-xs-1 text-right">Action</th>
					</tr>
				</thead>
				<tbody>
	    		<?php foreach ($this->paginator as $entity): $numleads = $entity->getCount(); ?>
	        		<tr class="leaditem">
						<td class="report.id col-xs-1"><div class="checkbox"><?php echo $this->formElement($form->get("sel[" . $entity->getId() . "]")); ?></div></td>
						<td class="col-xs-4 name"><a
							href="<?php echo ($numleads) ? $this->losUrl()->from('report/application/result/list',['id'=>$entity->getId(), 'action' => 'list'], true) : $this->losUrl()->from('report/edit',['id'=>$entity->getId()], true); ?>"
							title="<?php echo ($numleads) ? 'View Results' : 'Edit Report'; ?>"
							title="Edit Report"><?php echo $entity->getName(); ?></a></td>
						<td class="col-xs-2 account"><?php $account = $entity->getAccount(); echo $account ? '<a href="' . $this->url('account/view', ['action'=>'view', 'id' => $account->getId()]) . '">' . $account->getName() . '</a>' : 'None'; ?></td>
						<td class="col-xs-2 count"><?php if ($numleads) : ?><a
							href="<?php echo $this->losUrl()->from('report/application/result/list',['id'=>$entity->getId(), 'action' => 'list'], true)?>"><?php echo $numleads; ?> Lead(s)</a><?php else: echo "0 Leads"; endif; ?></td>
						<td class="col-xs-2 date"><?php echo date_format($entity->getUpdated(), 'd M, Y h:i A') ?></td>
						<td class="action col-xs-1 text-right"><a
							href="<?php echo ($numleads) ? $this->losUrl()->from('report/application/result/list',['id'=>$entity->getId(), 'action' => 'list'], true) : '#'; ?>"
							title="View Results"
							class="btn btn-xs btn-<?php echo (! $numleads) ? 'disabled disabled' : 'info'; ?>"><?php echo $this->losIcon('glyphicon-eye-open') ?></a>
							<a
							href="<?php echo $this->losUrl()->from('report/edit',['id'=>$entity->getId()], true)?>"
							title="Edit Report" class="btn btn-xs btn-warning"><?php echo $this->losIcon('glyphicon-edit') ?></a>
						</td>
					</tr>
				<?php endforeach;?>
				</tbody>
			</table>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>
<?php if ($this->paginator->count() > 1):?>
<div class="row">
	<div class="col-xs-12 text-center"><?php echo $this->losPaginationControl($this->paginator,'Sliding',null,['query'=>$this->query]); ?></div>
</div>
<?php endif?>
<?php echo $this->losHeadLink()->setBasePath('/js')->appendChosen()?>
<?php echo $this->losHeadScript()->setBasePath('/js')->appendChosen()?>

<script type="text/javascript">
<?php echo "var query = " . json_encode($this->query) . ";"; ?>
$(function(){
	$('.bulk-actions SELECT[id=accountfilter], .form-filter SELECT[id=accountfilter]').each(function(){
		var text = $(this).closest('.bulk-actions').length ? 'Choose Account' : 'Filter Account';
		$(this).initChosen({
			max: 1,
			resize: true,
			placeholder: text
		});
	});
});
</script>